apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage-data
  hostPath:
    path: /home/docker/data/master

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  storageClassName: redis-storage-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi