apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /data
      name: redis-data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-data
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf
